version: '3'
services:
  localstack:
    image: "localstack/localstack"
    environment:
      - SERVICES=kinesis,dynamodb,cloudwatch
      - HOSTNAME_EXTERNAL=localhost
    ports:
      - "4568:4568"
      - "4569:4569"
      - "4582:4582"