AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  notes-app

  Sample SAM Template for notes-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    Environment:
      Variables:
        HOST: none

Resources:
  CreateNoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handler.note.handler_create_note
      Runtime: python3.7
      Events:
        CreateNote:
          Type: Api
          Properties:
#           Can this be converted to a reference? so we have one JSON for path that is sharable
            Path: /notes
            Method: post
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:DeleteItem'
                - 'dynamodb:GetItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:UpdateItem'
                - 'dynamodb:Scan'
                - 'dynamodb:Query'
                - 'dynamodb:DescribeTable'
                - 'dynamodb:BatchWriteItem'
                - 'dynamodb:BatchGetItem'
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':table/*'

  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'Note'
      AttributeDefinitions:
        - AttributeName: note_id
          AttributeType: S
      KeySchema:
        - AttributeName: note_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  NotesAppBaseEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for Organization Module functionality"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    Export:
      Name: !Sub "${AWS::StackName}-NotesAppBaseEndpoint"